name: Download YouTube Playlist

on:
  repository_dispatch:
    types: [start-download]

jobs:
  yt-dlp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Python 3.9 and yt-dlp
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.9 python3.9-distutils python3.9-venv
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
        python3 --version
        pip3 install -U yt-dlp

    - name: Download Playlist Links
      run: |
        PLAYLIST_URL="${{ github.event.client_payload.playlist_url }}"
        yt-dlp -f "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]" --merge-output-format mp4 -g --flat-playlist "$PLAYLIST_URL" > links.txt

    - name: Commit and Push Playlist Links
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add links.txt
        git commit -m "Update playlist links"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/shyzemalik/YT.git HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
